import type { Forecast, RiskLevel } from "@/types/api";
import { CalendarDays, CheckCircle2, Info, Sprout } from "lucide-react";

const probabilityFields: Array<{ key: keyof Pick<Forecast, "onset_probability" | "false_onset_probability" | "dry_spell_5d_probability" | "severe_break_7d_probability" | "heavy_rain_probability" | "revival_probability">; label: string }> = [
  { key: "onset_probability", label: "Onset" },
  { key: "false_onset_probability", label: "False onset" },
  { key: "dry_spell_5d_probability", label: "Dry spell · 5d" },
  { key: "severe_break_7d_probability", label: "Severe break · 7d" },
  { key: "heavy_rain_probability", label: "Heavy rain" },
  { key: "revival_probability", label: "Revival" },
];
const levelColor: Record<RiskLevel, string> = { LOW: "bg-[#e3f2e7] text-[#266044]", MODERATE: "bg-[#fff1d7] text-[#93601d]", HIGH: "bg-[#ffe4d9] text-[#a94d2b]", VERY_HIGH: "bg-[#f8d9dc] text-[#9b2d3d]" };
const prettyLevel = (level: RiskLevel) => level.replace("_", " ");

export function ForecastSection({ forecast }: { forecast: Forecast }) {
  return <section className="animate-rise space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.18em] text-moss">Verified forecast layer</p><h2 className="font-display text-2xl font-semibold text-ink">{forecast.panchayat_name}</h2><p className="mt-1 text-sm text-slate-500">{forecast.block_name} · {forecast.district_name}</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><CalendarDays className="h-4 w-4" />Updated {new Date(forecast.timestamp).toLocaleString()}</div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{probabilityFields.map(({ key, label }) => <div key={key} className="border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">{label} probability</p><p className="mt-3 font-display text-3xl font-semibold text-ink">{(forecast[key] * 100).toFixed(1)}<span className="text-lg text-slate-400">%</span></p><div className="mt-3 h-1.5 bg-slate-100"><div className="h-full bg-moss" style={{ width: `${forecast[key] * 100}%` }} /></div></div>)}</div><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="border border-slate-200 bg-white p-5 sm:p-6"><div className="mb-5 flex items-center gap-2"><Info className="h-4 w-4 text-moss" /><h3 className="font-display text-lg font-semibold">Risk profile</h3></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(forecast.risk_levels).map(([name, level]) => <div key={name} className="border border-slate-100 p-3"><p className="mb-2 text-xs capitalize text-slate-500">{name.replaceAll("_", " ")}</p><span className={`inline-flex px-2 py-1 text-[11px] font-bold tracking-wide ${levelColor[level as RiskLevel]}`}>{prettyLevel(level as RiskLevel)}</span></div>)}</div></div><div className="border border-[#cde3d4] bg-[#edf7ef] p-5 sm:p-6"><div className="flex items-start gap-3"><Sprout className="mt-1 h-5 w-5 shrink-0 text-moss" /><div><p className="text-xs font-bold uppercase tracking-[.16em] text-moss">Agronomic advisory</p><h3 className="mt-2 font-display text-lg font-semibold text-ink">{forecast.advisory.headline}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{forecast.advisory.recommended_action}</p></div></div></div></div><div className="flex items-start gap-2 border-t border-slate-200 pt-4 text-xs leading-5 text-slate-500"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-moss" />{forecast.disclaimer}</div></section>;
}